cabal-version:      2.4

name:               whatevercc
version:            0.1.0.0
synopsis:           A superduperoriginal error-correcting-code project
build-type:         Simple

library
    hs-source-dirs:    src
    exposed-modules:
        WhatevErCC.GF2
        WhatevErCC.LinearAlgebra
        WhatevErCC.DeliciousHam
    build-depends:
        base >=4.14 && <5
    default-language: Haskell2010
    ghc-options:      -Wall

executable whatevErcc
    main-is:          Main.hs
    hs-source-dirs:   app
    build-depends:
        base >=4.14 && <5,
        whatevercc
    default-language: Haskell2010
    ghc-options:      -Wall